/**
 * 定数のバレルエクスポート
 */

// アプリケーション定数
export {
  APP_ICON,
  APP_NAME,
  APP_NAME_EN,
  APP_VERSION,
  AUTOSAVE_DELAY,
  CURRENT_PROJECT_ID,
} from "./app";

// 共通定数（Canvas/PDF共通）
export {
  DOSAGE_COLORS,
  FONT_SIZES,
  FONT_SIZES_SINGLE_COLUMN,
  LABELS,
  LAYOUT_COLUMNS,
  LINE_CLAMP,
  TEXT_LIMITS,
} from "./shared";

// エディタ定数（Canvas固有）
export {
  ANIMATION_STAGGER_DELAY,
  DEFAULT_PROJECT_TITLE,
  EDITOR_TEXT_STYLE,
  EDITOR_TEXT_STYLE_SINGLE_COLUMN,
  IMAGE_DRAG_TYPE,
  LAYOUT_OPTIONS,
  LONG_PRESS_DURATION,
  MAX_ITEM_COUNT,
  MAX_PRECAUTIONS_COUNT,
  PLACEHOLDER_IMAGE_COUNT,
} from "./editor";

// メッセージ定数
export {
  BUTTON_ADD_CARD,
  BUTTON_BACKUP,
  BUTTON_CANCEL,
  BUTTON_CONTINUE,
  BUTTON_DELETE,
  CANVAS_DROP_HERE,
  CANVAS_EMPTY_DESCRIPTION,
  CANVAS_EMPTY_TITLE,
  createDeleteAllDialogDescription,
  createDeleteAllDialogTitle,
  createDeleteAllLabel,
  createDisplayedImagesDeleteMessage,
  createImageDeleteSuccessMessage,
  createMaxItemCountReachedMessage,
  createSelectedImagesDeleteDescription,
  createSelectedImagesDeleteLabel,
  CTA_BUTTON_LABEL_CREATE,
  CTA_BUTTON_LABEL_RESUME,
  CTA_BUTTON_LABEL_TRY,
  DELETE_CONFIRM_DESCRIPTION,
  DELETE_CONFIRM_TITLE,
  DELETE_SUCCESS_MESSAGE,
  EXPORT_JSON_LABEL,
  EXPORT_ZIP_LABEL,
  GRID_SELECT_BUTTON_LABEL,
  GRID_SELECT_MODAL_DESCRIPTION,
  GRID_SELECT_MODAL_TITLE,
  HOME_LINK_TOOLTIP,
  IMAGE_DELETE_DESCRIPTION,
  IMAGE_DELETE_SELECTED_TITLE,
  IMAGE_DELETE_TITLE,
  IMAGE_LIBRARY_BULK_DELETE,
  IMAGE_LIBRARY_BULK_DELETE_END,
  IMAGE_LIBRARY_CAMERA_SHORT,
  IMAGE_LIBRARY_CAMERA_SUCCESS,
  IMAGE_LIBRARY_CATEGORY_PLACEHOLDER,
  IMAGE_LIBRARY_CLICK_INSTRUCTION,
  IMAGE_LIBRARY_CLIPBOARD_NOT_ALLOWED,
  IMAGE_LIBRARY_DELETE_SELECTED,
  IMAGE_LIBRARY_DROP_INSTRUCTION,
  IMAGE_LIBRARY_GALLERY,
  IMAGE_LIBRARY_GALLERY_SHORT,
  IMAGE_LIBRARY_NO_IMAGE_IN_CLIPBOARD,
  IMAGE_LIBRARY_NO_MATCHES,
  IMAGE_LIBRARY_PASTE,
  IMAGE_LIBRARY_PASTE_FAILED,
  IMAGE_LIBRARY_PASTE_SHORT,
  IMAGE_LIBRARY_PASTE_SUCCESS,
  IMAGE_LIBRARY_UPLOADING,
  IMAGE_LIBRARY_VIDEO_NOT_SUPPORTED,
  IMAGE_PROCESSING_ERROR_MESSAGE,
  IMAGE_UPLOAD_WARNING,
  IMPORT_CONFIRM_DESCRIPTION,
  IMPORT_CONFIRM_TITLE,
  IMPORT_ERROR_CORRUPTED_ZIP,
  IMPORT_ERROR_EXTRACTED_TOO_LARGE,
  IMPORT_ERROR_FILE_TOO_LARGE,
  IMPORT_ERROR_INVALID_FORMAT,
  IMPORT_ERROR_NO_PROJECT,
  IMPORT_ERROR_TOO_MANY_IMAGES,
  IMPORT_ERROR_VALIDATION,
  IMPORT_FAILED_MESSAGE,
  IMPORT_LOADING_LABEL,
  IMPORT_OPEN_LABEL,
  IMPORT_SUCCESS_MESSAGE,
  LABEL_PROJECT_TITLE,
  MOBILE_TAP_TO_SELECT_IMAGE,
  PDF_DOWNLOAD_LABEL,
  PDF_DOWNLOAD_SUCCESS,
  PDF_GENERATE_FAILED,
  PDF_GENERATING_MESSAGE,
  PDF_GENERATING_SHORT,
  PDF_MENU_LABEL,
  PDF_NO_CARDS_ERROR,
  PDF_PREVIEW_EXPAND_TOOLTIP,
  PDF_PREVIEW_FULLSCREEN_TOOLTIP,
  PDF_PREVIEW_GENERATING,
  PDF_PREVIEW_LABEL,
  PDF_PREVIEW_TITLE,
  PROJECT_DELETE_CONFIRM_DESCRIPTION,
  PROJECT_DELETE_CONFIRM_TITLE,
  PROJECT_DELETE_SUCCESS_MESSAGE,
  PROJECT_DELETE_TOOLTIP,
  PROPERTY_PANEL_WARNING,
  SECURITY_DISCLAIMER_AGREE_BUTTON,
  SECURITY_DISCLAIMER_CHECKBOX_LABEL,
  SECURITY_DISCLAIMER_DEVICE_DESCRIPTION,
  SECURITY_DISCLAIMER_DEVICE_TITLE,
  SECURITY_DISCLAIMER_INCOGNITO_DESCRIPTION,
  SECURITY_DISCLAIMER_INCOGNITO_TITLE,
  SECURITY_DISCLAIMER_PRIVACY_DESCRIPTION,
  SECURITY_DISCLAIMER_PRIVACY_TITLE,
  SECURITY_DISCLAIMER_SCROLL_HINT,
  SECURITY_DISCLAIMER_SECURITY_DESCRIPTION,
  SECURITY_DISCLAIMER_SECURITY_TITLE,
  SECURITY_DISCLAIMER_TERMS_LINK,
  SECURITY_DISCLAIMER_TITLE,
  UNKNOWN_ERROR_MESSAGE,
  WORKER_ERROR_MESSAGE,
} from "./messages";

// 画像定数
export type { ImageFilterCategory } from "./image";
export {
  ALLOWED_IMAGE_TYPES,
  DEFAULT_IMAGE_FILTER,
  IMAGE_ACCEPT_TYPES,
  IMAGE_DISPLAY_NAME_NUMBER_PATTERN,
  IMAGE_DISPLAY_NAME_PREFIXES,
  IMAGE_FILTER_CATEGORIES,
  IMPORTED_IMAGE_FILTER,
  MAX_FILE_SIZE,
  MAX_IMPORT_JSON_SIZE,
  MAX_IMPORT_ZIP_SIZE,
  MAX_ZIP_EXTRACTED_SIZE,
  MAX_ZIP_IMAGE_COUNT,
} from "./image";

// サンプル画像定数
export type { SampleImage } from "./sampleImages";
export {
  getSampleImageFileName,
  getSampleImagePath,
  isSampleImage,
  SAMPLE_IMAGE_ID_PREFIX,
  SAMPLE_IMAGES,
} from "./sampleImages";

// 更新履歴定数
export {
  CATEGORY_COLOR_CLASSES,
  CATEGORY_LABELS,
  CATEGORY_ORDER,
  RECENT_ENTRIES_COUNT,
} from "./changelog";

// PDF定数（PDF固有）
export {
  CJK_PATTERN,
  getPdfContentSize,
  getPdfPageSize,
  isLandscapeLayout,
  PDF_CARD_STYLE,
  PDF_COLORS,
  PDF_CONTENT_SIZE,
  PDF_CONTENT_SIZE_LANDSCAPE,
  PDF_DOSAGE_COLORS,
  PDF_FONT_FAMILY,
  PDF_FONT_PATHS,
  PDF_GRID_GAP,
  PDF_HEADER_HEIGHT,
  PDF_IMAGE_ASPECT_RATIO,
  PDF_LABELS,
  PDF_MARGINS,
  PDF_PAGE_SIZE,
  PDF_PAGE_SIZE_LANDSCAPE,
  PDF_SPACING,
  PDF_SUPPORTED_IMAGE_PREFIXES,
  PDF_TEXT_STYLE,
} from "./pdf";

// テンプレート定数
export {
  TEMPLATE_APPLY_SUCCESS,
  TEMPLATE_BASE_PATH,
  TEMPLATE_BUTTON_LABEL,
  TEMPLATE_CARD_COUNT_LABEL,
  TEMPLATE_CONFIRM_BUTTON,
  TEMPLATE_CONFIRM_DESCRIPTION,
  TEMPLATE_CONFIRM_TITLE,
  TEMPLATE_INVALID_DATA_ERROR,
  TEMPLATE_LOAD_ERROR,
  TEMPLATE_LOADING_LABEL,
  TEMPLATE_MODAL_DESCRIPTION,
  TEMPLATE_MODAL_TITLE,
  TEMPLATE_NOT_FOUND_ERROR,
} from "./template";

// 定型文（スニペット）定数
export type {
  PrecautionSnippet,
  PrecautionSnippetCategory,
  PrecautionSnippetCategoryId,
} from "./precautions";
export {
  PRECAUTION_SNIPPET_CATEGORIES,
  PRECAUTION_SNIPPETS,
  SNIPPET_ADD_BUTTON_LABEL,
  SNIPPET_BUTTON_LABEL,
  SNIPPET_DIALOG_DESCRIPTION,
  SNIPPET_DIALOG_TITLE,
  SNIPPET_MAX_EXCEEDED_MESSAGE,
} from "./precautions";

// モーダル定数
export {
  SECURITY_DISCLAIMER_EXPIRY_MS,
  SECURITY_DISCLAIMER_SESSION_KEY,
  SECURITY_DISCLAIMER_TIMESTAMP_KEY,
} from "./modal";

// 外部リンク定数
export {
  ALLOWED_EXTERNAL_URLS,
  FEEDBACK_FORM_URL,
  GITHUB_ISSUES_URL,
  GITHUB_LICENSE_URL,
  GITHUB_REPO_URL,
} from "./externalLinks";
